### ISSUE TITLE
Please sign tarball

### ISSUE THREAD

**Issue by Natureshadow** [pallets-eco/flask-mail#145]
I am maintaining Flask-Mail in Debian, which preferes cryptographic verification of upstream tarballs.

Please sign the source tarball on PyPI if at all possible.

**Comment by davidism** [comment]
Our new publish workflow generates SLSA provenance for the build and places that in the GitHub release, as Flask and other Pallets projects do. PyPI no longer docs pgp signatures, but is currently working on their own provenance support as part of trusted publishing.

**Comment by Natureshadow** [comment]
All hail to the ever-trustworthy, centralised Microsoft platform!

**Comment by davidism** [comment]
Note that this does not mean that we are tied to the GitHub platform. PyPI trusted publishing already works with multiple platforms and more are being added. SLSA provenance is not part of GitHub, nor is PyPI's own provenance support. The provenance is hosted on GitHub release pages because that is a place we can easily host it. If we moved to another source host, we would presumably build provenance and put it there instead. Sarcastically commenting about our (a group of volunteers working in our free time) use of a convenient and popular git service is not productive or appreciated, and will not helping you get support.
