### ISSUE TITLE
CRLF injection in flask_mail.Message.send()

### ISSUE THREAD

**Issue by lwzSoviet** [pallets-eco/flask-mail#189]
There is a CRLF vulnerability in python/Lib/smtplib.py and you can see details in [https://bugs.python.org/issue43124](https://bugs.python.org/issue43124), I review some web framework like Django,Flask and Bottle,etc. and find this vulnerability exists in flask_mail.py.Message.send(), The Poc is:
```
from flask import Flask
from flask_mail import Message, Mail
app = Flask(__name__)
app.config.update(
    MAIL_SERVER = '127.0.0.1',
    MAIL_PORT = 10001,
)
@app.route("/")
def hello_world():
    msg = Message("Hello",
                  sender="from@example.com",
                  recipients=["to@example.com"],
                  mail_options=["X-OPTION\nBad smtp-client command1","X-OPTION2\nbad smtp-command2"])
    mail = Mail(app)
    mail.send(msg)
if __name__=='__main__':
    app.run(debug=True)
```
Output:
![image](https://user-images.githubusercontent.com/30397594/127487841-b3721415-0fd1-4c1b-9adc-1b377af29300.png)
In flask_mail.py,function send() calls sendmail(), but not check if CRLF in message.mail_options or message.rcpt_options.

**Comment by davidism** [comment]
If you believe you have found a security issue in python, then you should follow their security reporting guidelines to privately disclose it.

Note that `mail_options` does not seem to be an API intended for untrusted user input in the first place. It's not clear why you would expect users to enter data that would go there (as opposed to subject, body, recipient, etc.). Therefore, I'd probably classify this as a security issue with the application doing that instead of this library.
