### ISSUE TITLE
SMTP.quit() called when not connected

### ISSUE THREAD

**Issue by tlynn** [pallets-eco/flask-mail#93]
Connection.__exit__() tries to call quit() even if there's no socket connection.  "if self.host" should say "if self.host and getattr(self.host, 'sock', None)" to match the check in smtplib.SMTP.quit().

**Comment by Garito** [comment]
Hi!
I posted this issue: https://github.com/mattupstate/flask-mail/issues/98 that perhaps has to do with this error because the exim people said to me that the error was caused by the app (flask-mail?)

Seems that the app closes the connection before end the sending so SMTPServerDisconnected: please run connect() first is raised

I have some exim logs to ilustrate this problem @ http://pastebin.com/EPCcfj6e

Hope this will help because I still have random errors 

Thanks!

**Comment by tlynn** [comment]
This issue should really be sorted by now, I included the required fix in the first comment (and justified it in the second).

**Comment by Garito** [comment]
But is this pushed already?
Need to fix the error

**Comment by Garito** [comment]
So, can you push the correction to pypi?
My app don't stop raising errors because of that
And my users are starting to be nervous, they ask me to change this library or do something about

**Comment by davidism** [comment]
I'm not clear how this issue can happen. We don't call `exit()`, and `SMTP.quit()` does not have the check you indicate it does. The following code does not seem to have any issue. If you still have an issue, please open a new issue with a minimal reproducible example and clear description.

```python
from flask import Flask
from flask_mail import Mail, Message

app = Flask(__name__)
app.config.update({
    "MAIL_HOST": "127.0.0.1",
    "MAIL_PORT": 1025,
})
mail = Mail(app)

with app.app_context():
    with mail.connect() as c:
        c.send(Message("test", sender="test", recipients=["test"]))
```
